openapi: 3.0.0
info:
  version: 2.1.0
  title: RIC a1orchict
paths:
  '/prb-pred/healthcheck':
    get:
      description: >
        Perform a healthcheck on a1orchict
      tags:
        - a1orchict Xapp
      operationId: a1orch.api.get_healthcheck
      responses:
        200:
          description: >
            A1 is healthy.
            Anything other than a 200 should be considered a1 as failing