apiVersion: v1
entries:
  alloc:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-10-24T14:06:00.226341037Z"
    description: Standard xApp Helm Chart
    digest: 5654422fdf637ac63dae066335cde622c943c30ee79d6b57bf65cdf5ec2d8a77
    name: alloc
    urls:
    - charts/alloc-0.0.2.tgz
    version: 0.0.2
  prbpredxapp:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-10-24T17:56:38.324091537Z"
    description: Standard xApp Helm Chart
    digest: eb773f1dfaa3a3749cf8dc3236c4a5162baec049c871b7415a62595df23a0630
    name: prbpredxapp
    urls:
    - charts/prbpredxapp-1.0.0.tgz
    version: 1.0.0
generated: "2021-10-24T17:56:38Z"
serverInfo: {}
